# re-usable data configuration
ds_type: 'sampled' # type of predictors [toy, flat, scm, sampled, mixed]
source: 'all' # source dataset (ignored, unless ds_type == 'sampled')
likelihood_family: 1 # 0 = normal, 1 = bernoulli, 2 = poisson
max_d: 12 # maximum number of fixed effects (intercept + slopes)
max_q: 3 # maximum number of random effects (intercept + slopes)
min_m: 5 # minimum number of groups
max_m: 180 # maximum number of groups
min_n: 4 # minimum number of samples per group
max_n: 70 # maximum number of samples per group
max_n_total: 6400 # maximum total number of samples
