"""Numerical constants for analytical GLMM estimators."""

_EIGH_JITTERS = [1e-6, 1e-4, 1e-2, 1.0]
_BERNOULLI_INITIAL_PSI_FLOOR = 0.25
_BERNOULLI_HG_INV_EIG_CAP = 25.0
_BERNOULLI_PSI_EIG_CAP = 49.0
_BERNOULLI_BLUP_VAR_INFLATION = 1.5
_BERNOULLI_CORR_SHRINKAGE_C = 10.0
_BERNOULLI_BLUP_KH_VAR_CAP = 0.2
_BERNOULLI_HIGH_D_BLUP_VAR_FLOOR = 0.25
_POISSON_ETA_CLIP_MAX = 10.0
_POISSON_INITIAL_PSI_FLOOR = 0.01
_POISSON_HG_INV_EIG_CAP = 25.0
_POISSON_PSI_EIG_CAP = 25.0
_POISSON_CORR_SHRINKAGE_C = 20.0
_POISSON_ETA_TAPER_WIDTH = 0.5
_POISSON_BETA_CLAMP = 10.0
_POISSON_BLUP_CLAMP = 10.0
_NORMAL_Z_COND_CAP = 1e6
_NORMAL_RANK_REL_TOL = 1e-5
_NORMAL_RANK_ABS_TOL = 1e-8
_NORMAL_FULL_MIN_EM = 5
