# experiment
name: 'hyper'
d_tag: 'toy'          # points to metabeta/simulation/configs/toy.yaml
d_tag_valid: 'toy'    # validation data config tag
m_tag: 'toy'          # points to metabeta/models/configs/toy.yaml
seed: 42

# runtime
device: 'cuda'         # cpu|cuda|mps
cores: 8
reproducible: true
compile: false
verbosity: 1          # warnings|infos|debug
wandb: true

# training
max_epochs: 30
bs: 32                # batch size
lr: 1.0e-3
max_grad_norm: 1.0
loss_type: 'forward'  # forward|backward|mixed
patience: 5           # early stopping
sample_interval: 5
skip_ref: true        # skip reference run before training

# evaluation
n_samples: 512        # posterior draws
rescale: true         # unstandardize y
importance: false     # importance sampling
sir: false            # sampling importance resampling
sir_iter: 8
plot: false

# checkpoint
r_tag: ''             # run tag
save_latest: false
save_best: true
load_latest: false
load_best: false
