# experiment
name: 'large-p-sampled'
d_tag: 'large-p-sampled'          # points to metabeta/simulation/configs/*.yaml
d_tag_valid: 'large-p-sampled'    # validation data config tag
m_tag: 'large'                    # points to metabeta/models/configs/*.yaml
seed: 42

# runtime
device: 'cpu'         # cpu|cuda|mps
cores: 8
reproducible: false
compile: false
verbosity: 1          # warnings|infos|debug
wandb: false

# training
max_epochs: 10
bs: 32                # batch size
lr: 1.0e-3
max_grad_norm: 1.0
loss_type: 'forward'  # forward|backward|mixed
patience: 10          # early stopping
sample_interval: 5
skip_ref: false       # skip reference run before training

# evaluation
n_samples: 512        # posterior draws
rescale: true         # unstandardize y
importance: false     # importance sampling
sir: false            # sampling importance resampling
sir_iter: 8
plot: true

# checkpoint
r_tag: ''             # run tag
save_latest: true
save_best: true
load_latest: false
load_best: false
