summarizer:
    type: 'set-transformer'
    d_model: 64 # [64, 128]
    d_ff: 128 # 2x d_model
    d_output: 32 # 0.5x d_model
    n_blocks: 4 # [2, 4, 6]
    n_isab: 0
    activation: 'GELU'
    dropout: 0.01

posterior:
    type: 'coupling'
    transform: 'affine'
    base_family: 'normal'
    base_trainable: True
    n_blocks: 3 # [3, 5]
    subnet_kwargs:
        net_type: 'mlp'
        activation: 'ReLU'
        d_ff: 128 # [128, 196, 256]
        depth: 3 # [2, 3]
        dropout: 0.01
        zero_init: True
        use_bias: False
